# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'SSOfflineMapKit' do

pod 'SSZipArchive', '~> 1.4'
pod 'ARSPopover', '~> 2.2'

end

